### PR TITLE
Add more model tests

### PR DESCRIPTION
**Pull request by DerekStride**
I'm adding tests for Comments, Likes, Photos, and Posts.

### CODE REVIEW

**Comment by DerekStride** [comment]
I had a problem with the `Faker::Posts`

```ruby
num_users = User.count
Post.new(
  author_id: (rand * num_users).ceil,
  receiver_id: (rand * num_users).ceil
)
```

Here if we create a User in the test framework, it'll create a User with an id of 1 as we expect, **but** when the database gets cleared and the end of the test case and starts running the next one. If it creates a user it'll create one with an id of 2 not a user with an id of 1 like we'd need it to do for the above code to work.

**Comment by justinkrol** [comment]
^ #33 should fix this

**Comment by DerekStride** [comment]
Should be good to go now since I'm using FactoryGirl from #34

**Comment by DerekStride** [comment]
This closes https://github.com/GraphQL-Query-Planner/project/issues/13 and #25

**Pull request merged**
