### PR TITLE
Add graphql rake tasks

### PR DESCRIPTION
**Pull request by DerekStride**
Also fixed some broken tests. 🚢

### CODE REVIEW

**Comment by ismail-syed** [comment]
Failing tests?

**Comment by DerekStride** [comment]
Yeah, I have more to fix now 👀

**Comment by DerekStride** [comment]
It looks like the parsing of the explain output on CI is different from that of development. I'm working on debugging on CI but for the moment I'm going to skip the test.

**Comment by DerekStride** [comment]
I've fixed the issues, Travis uses MySQL 5.6 and has a different explain output. I had to contact support and enabled debug builds so if you need to debug CI let me know.

**Pull request merged**
